{% set name = "tempora" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61287665ed38bb86a3f4293de5c7613c56b525f9db2ec099d794b9c97f7d5e54


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - calc-prorate = tempora:calculate_prorated_values


requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0
  run:
    - python >=3.6
    - pytz
    - jaraco.functools >=1.20

test:
  imports:
    - tempora

about:
  home: https://github.com/jaraco/tempora
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Objects and routines pertaining to date and time (tempora)
  dev_url: https://github.com/jaraco/tempora

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
