travis:
  secure:
    BINSTAR_TOKEN: qtbs45u19+LVDiqHBysE3PwqHRyzmicnncf11j7wmrGBksemdp6hpal5W5lRXQWiOJXzyj1LdsFy5gsb4B7GQRyBng1JjqCg3NEvG14T9uw0IxEL7zWui7ozcqm7mNW3O/kMknQ5gwaEA2ZfFnEWDixM5hhKrMxSiYB7HQjEu1hGYF5tvRduxkFMFla9hD9kr3BpxrAAt1C7MRuMDkrTVnV5rJnv7xzc3VR3QZKw5Vy+ScGQCg3ElXhuiLSROgN9jAOAip5YpQif7VpN2/riMiFXmXFNJKviCoavxtDPOJneCPazdFDXWwfctxThqKi78sW97V+x7PH5ib4VevzwxsmSF9V4X3ZUAISC6oP3rjqbfC9RkMGvKN31mg2Or3TQC832c5P7v+/KUK0dIGDhJ2EVxobgI4tL41Ru5CoJ7bca9YuOBpz5/+tP68qASD6uqKDEDKXwGAEW9CKtBUQaLpDqy+t1ejDpL+ETI5fWaJf0NSIbDoClhQyq3qbf9vAAgYpGwgVzdlywv0IqMAbIC/F12+CRJ722TnNBD3SRuBNBE38hHq152wkYNnU7hf0t33Ld4DCfOMdq96S0bIjetbOtI8XQ4xqtIphyAq/7+wY1UArJJc3oD1IHqu0CV0Ai/eGGv6DWTm3DgXaaaQ/ylfGUxzPsKhxbsEp1ZQPwZiw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
