travis:
  secure:
    BINSTAR_TOKEN: n2O9adnzMtYLAHJlknUjZjSPs77p8izijTKi6ozAJSWQBhXluq0KcVQsUQtAUgJ6jOZv0bEfvSHCNEDXsRVlRti0YrXgvOkfAyhg54nqxlrfJjRMkCtOCb/Is4/1OkjlgC73ZggGJYwziP3IIAV8ZxCL24F/pgcUcmYOzdQW1aFqmqwavwrmQac6cCebfuqPTbc/mdqGLS7pSMoMalJpn3Id5pukK5gb0ip7UUh5E5ax0UGZsqsSjYgTfB/578OubvRz9K8BmYAo8hPiQV+l0+p7RScL85S3xlHgbRJvtzKHBjN7bO2PaMhftFcSFANacgPE8669P9rpD7yrFxmgoohTYArsAOZGw/EMc2ObDIl+HzYn/TNPf5Dz5al2Z0ccTA9dZPCXEAkgK3YsWaUA5xitDO7fEnZqKrVO6dRVOZnlr8GuXkppysxVDzBxZtxKs9JVhjFL5vlTIIDOqOcbQuXg4vrj0xG+HhCEwchfj1FHbjK3K+HaZiQVTPvpgILRLV0KH8hYbUp9uJQCkZCu8lwsfbhIqcJV+ms+t11aiDQghcVj2F95YclcpuehwlD6SL6NgTo3wrtEhGWQQSnYJ1yx2FSoyCD0BF2r9yOsrqDc4QJ1TWjQTRjw5jS35WhQVSVDtG7wrfLPeTRmRg4Tu51+bIu61xPElTuPj0CqqrA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
