travis:
  secure:
    BINSTAR_TOKEN: 3urDY4/84FkiRPKxdoVnN91YNWCqI7l9fmks1AO+oTTx5G7ehQqkTJ39S3djMafN/L8jQCrVZ3GUHFpnNFaPsHj5BtbCzYuVlKmQJ+562yc4KR2Zcn501rr8pM6HfcpJmC+RizPJ7Z50eU5v7QKZzWefrOL34Etz//Be9Wz5vd1SfgQHr9fwMSUfcwjtmQYy3OgPV/NjXayjQFwJifI+jElsnWaBbJI+mR1VefFmvwMsh4hGXgJGg4qDaHBGHXLiqfupit498xPR+ZkSX5vSMwMxFwSpBr4JmXsgNusKfM0iqMyl/ZLkqgrqz2N2MLbjVw/OS0a4lsDNRjDgwDJUgIOZjnS4UURZkFuGfcpkCXWZyi0Xv4wu+ENg5hV949R9TFlm0V7V+yRVuiMGNZkAJ4UYiWQfCmESiFPOOIkOCNfL2knNIETTlzLLUzV5kDerU2KUcSHrOOMT4DKK+bEAAXH/3qWQ+KZuD2+hYBTEV43oBotOFIvn6TkQfD6EcnbaYq2sH5wEJy+s4Up0+OdlylL1VZZej+eecdaE/X5wghLmgbDBKmoEckBTBh6F7VqUa6g8hy3qT54mXmnlEp91fb1nTOwGC/qipuMmoObUquwKUG5770qs5Q0FyXUqdBkTISJ+fDpNaUFTIDVcWpGm+q60gDkTc1scIF7Q0D1X4IQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
